# Generated by Django 5.1.7 on 2025-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_payments_stripe_session_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_status",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Статус оплаты в Stripe",
            ),
        ),
    ]