# Generated by Django 5.2 on 2025-04-28 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название курса', max_length=255, verbose_name='Название')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите изображение курса', null=True, upload_to='courses/previews', verbose_name='Превью')),
                ('description', models.TextField(blank=True, help_text='Введите описание курса', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название урока', max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Введите описание урока', null=True, verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите изображение урока', null=True, upload_to='lessons/previews', verbose_name='Превью')),
                ('video_url', models.URLField(blank=True, help_text='Введите ссылку на видеоурок', null=True, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(blank=True, help_text='Выберите курс, к которому относится урок', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
