name: Django CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

      - name: Run migrations
        env:
          TEST_ENV: true
        run: python manage.py migrate

      - name: Run tests
        env:
          TEST_ENV: true
        run: python manage.py test

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} \
              "echo 'SSH connection established successfully'"

      - name: Install rsync if not exists
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Sync project files
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --exclude '.git' \
            --exclude '.github' \
            --exclude '.env' \
            --exclude '__pycache__' \
            --exclude '*.pyc' \
            --exclude '*.pyo' \
            --exclude '*.pyd' \
            ./ \
            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_PATH }}

      - name: Install dependencies on server
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} \
              "cd ${{ secrets.DEPLOY_PATH }} && \
               python -m pip install --upgrade pip && \
               pip install -r requirements.txt"

      - name: Run migrations on server
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} \
              "cd ${{ secrets.DEPLOY_PATH }} && \
               python manage.py migrate --noinput"

      - name: Collect static files
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} \
              "cd ${{ secrets.DEPLOY_PATH }} && \
               python manage.py collectstatic --noinput"

      - name: Restart application server
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} \
              "sudo systemctl restart gunicorn || \
               sudo systemctl restart apache2 || \
               echo 'No web server restarted'"

      - name: Verify deployment
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} \
              "cd ${{ secrets.DEPLOY_PATH }} && \
               ls -la && \
               python manage.py check --deploy"